### ISSUE TITLE
Can't Cmake on Mac OS 10.10.2

### ISSUE THREAD

**Issue by MatthewFrench** [Jebbs/DSFML-C#15]
Matthews-MacBook-Pro:DSFML-C-master Matt$ cmake /Users/Matt/Downloads/DSFML-C-master 
CMake Error at cmake/Config.cmake:28 (message):
  Unsupported version of OS X : 10.10.2
Call Stack (most recent call first):
  CMakeLists.txt:20 (include)

**Comment by Jebbs** [comment]
Just did a quick search. This is due to some internals not being correct in the REGEX on that line.

If you replace that particular line with this:
```STRING(REGEX REPLACE "10\\.([0-9]+).*" "\\1" MACOSX_VERSION "${MACOSX_VERSION_RAW}")```

It should work. I'll do a patch real quick.

**Comment by Jebbs** [comment]
Just wanted to actually make sure that did in fact fix your issue.
