### ISSUE TITLE
MSVC - force unicode over multi-byte characterset

### ISSUE THREAD

**Issue by neagix** [Jebbs/DSFML-C#8]
A small improvement: by default CMake will build VC++ projects that build with the default multi-byte characterset instead of Unicode. Since Windows XP all multi-byte strings are converted internally to Unicode before usage in Windows APIs, thus going native is good both for compatiblity (long live UTF-8!) and performance reasons.

```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -18,6 +18,11 @@ set(VERSION_MAJOR 2)
 set(VERSION_MINOR 0)
 set(VERSION_PATCH 0)

+# force Unicode over Multi-byte
+if(COMPILER_MSVC)
+    add_definitions(-DUNICODE -D_UNICODE)
+endif()
+
 # add the CSFML header path
 include_directories(${CMAKE_SOURCE_DIR}/include)

```

NOTE: I tested this only with Visual Studio 2010, targeting 64bit:

```
cmake -G "Visual Studio 2010 Win64" ..
```

**Comment by KyrietS** [comment]
Sorry for digging up this old thread but it appears to be well-indexed by Google when you search "CMake unicode character set". I just want CMake to generate Visual Studio Solution with this value set to "`Use Unicode Character Set`":
![image](https://github.com/Jebbs/DSFML-C/assets/19170699/e3397227-b2c7-4a72-85f9-a692b405184b)

**It is a shame** that in 2023 CMake still generates Visual Studio Solutions with **Character Set** set to "`Use Multi-Byte Character Set`" and the only option to override this is adding preprocessor definitions in CMake.

 Anyway, in "mordern" CMake the use of `add_definitions` is discouraged. So now it would be:

```cmake
 if (MSVC)
     target_compile_definitions(my_target PUBLIC UNICODE _UNICODE)
 endif()
```
